---
title: "Asking Good Questions"
author: "Carlos Gerez"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:  
    keep_md: true
    toc: true
    toc_float: true
    code_folding: hide
    fig_height: 6
    fig_width: 12
    fig_align: 'center'
---

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```



## Background
#### This is a first approach to the semester Project Questions.
Questions  

1.	Does are a correlation between education level and economical level in between countries globally? Can we find a trend? Why does that happen?  
2.	Compare the energy production by country with its economical level. Who are the countries that produce/consume more energy? What is his impact?  
3.	Have food prices decreased in time by country? How does that impact nutrition?  
4.	How is education changing the world? Is a correlation between health, economy and education?



## Conclusions

#### Most of the people I talked liked the questions. However they insist i some point to take in account:  
- Find from where you can get and download the data for this topics.  
- Start to think on how you can visually express a solution to the questions.  
- Be sure to satisfy all the wrangling requirements.  

This are links to places with interesting insights and in some cases data on each question:  

1. 
    - I found this link to an interesting article from: [Education Next](https://www.educationnext.org/education-and-economic-growth/)  
    - I found great visualizations in this page from: [Our World in Data](https://ourworldindata.org/global-education)  
    <br/><br/>
2. 
    - Related to the question Are developed countries producing/consuming more energy? I found this useful: [Center on Global Energy Policy](https://www.energypolicy.columbia.edu/publications/energy-and-development-changing-world-framework-21st-century/) and this short article from [BBC.](https://www.bbc.co.uk/bitesize/guides/zpmmmp3/revision/3)  
    - On the question What is his impact? I found this paper interesting: [National Library of Medicine.](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9328951/)  
    <br/><br/>
3. 
    - Related to: Have food prices decreased in time by country? found this information in [Our World in Data](https://ourworldindata.org/food-prices) and in [FAO from the United Nations.](https://www.fao.org/worldfoodsituation/foodpricesindex/en/)  
    - On how does that impact nutrition? from the [World Bank.](https://www.worldbank.org/en/programs/icp/brief/foodpricesfornutrition)  
    <br/><br/>
4. 
    - About how education is changing the world? in [Our World in Data.](https://ourworldindata.org/grapher/average-years-of-schooling-vs-gdp-per-capita)  
    - On a correlation between health, economy and education [from OECD.stat](https://stats.oecd.org/Index.aspx?QueryId=93449) and [Archives of Public Health.](https://archpublichealth.biomedcentral.com/articles/10.1186/s13690-020-00402-5)
